services:

  redis:
    image: redis:8.0.3
    hostname: redis-master
    # Not enabling password for now
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - redis-server
      - --maxmemory
      - 64mb
      - --maxmemory-policy
      - allkeys-lru
      - --appendonly
      - no
      - --save
      - ""
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
    ports:
      - "6379:6379"
    networks:
      - local_network
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 68m

networks:

  local_network:
    driver: bridge