# docker-compose.prod.yml
version: "3.9"

services:
  app:
    image: ghcr.io/${GHCRIO_USERNAME}/${PROJECT_ARTIFACT_ID}:${PROJECT_VERSION}
    environment:
      DEBUG_ENABLED: false
      JAVA_OPTS: -Xms256m -Xmx1g
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

  redis:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

  postgres:
    image: postgres:15
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      placement:
        constraints:
          - node.labels.type == database

networks:
  app-net:
    driver: overlay # Use overlay network for Docker Swarm