version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
      # Remote debug port for IntelliJ
      - "5005:5005"
    environment:
      - DEBUG_ENABLED=true
      - DEBUG_PORT=5005
      - JAVA_OPTS=-Xms256m -Xmx1g
    volumes:
      # Optional: for live code reload
      - .:/app
    depends_on:
      - redis

  redis:
    ports:
      - "6379:6379"
