services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    hostname: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_SUPER_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_USER_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPER_USER_NAME} -d ${POSTGRES_DB_NAME}"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local_network

volumes:
  postgres_data:

networks:

  local_network:
    driver: bridge