version: "3.9"

services:
  app:
    # prebuilt, pushed image
    image: my-app:latest
    environment:
      - DEBUG_ENABLED=false
      - JAVA_OPTS=-Xms256m -Xmx1g
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

  redis:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

networks:
  app-net:
    driver: overlay
