CREATE TABLE IF NOT EXISTS "APP_ROLE" (
    "ROLE_ID" BIGSERIAL PRIMARY KEY NOT NULL,
    "ROLE_NAME" VARCHAR(31) UNIQUE NOT NULL,
    "ROLE_DESCRIPTION" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "USER_GROUP" (
    "USER_GROUP_ID" BIGSERIAL PRIMARY KEY NOT NULL,
    "GROUP_NAME" VARCHAR(31) UNIQUE NOT NULL,
    "GROUP_DESCRIPTION" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "APP_USER" (
    "APP_USER_ID" BIGSERIAL PRIMARY KEY NOT NULL,
    "USER_NAME" VARCHAR(31) NOT NULL,
    "PASSWORD" VARCHAR(31) NOT NULL,
    "USER_EMAIL" VARCHAR(127) UNIQUE NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    "LAST_UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS "ROLE_GROUP_MAPPING" (
    "ROLE_ID" BIGINT NOT NULL,
    "USER_GROUP_ID" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "USER_GROUP_MAPPING" (
    "APP_USER_ID" BIGINT NOT NULL,
    "USER_GROUP_ID" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "ORGANISATIONS" (
    "ORG_ID"     BIGSERIAL PRIMARY KEY,
    "ORG_NAME"   TEXT        NOT NULL,
    "IS_ACTIVE"  BOOLEAN     NOT NULL DEFAULT TRUE,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    "LAST_UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);


CREATE TABLE IF NOT EXISTS "CLIENT_APPLICATIONS" (
    "CLIENT_APP_ID"   BIGSERIAL PRIMARY KEY,
    "CLIENT_APP_NAME" TEXT        NOT NULL,
    "ORG_ID"          BIGINT      NOT NULL,
    "IS_ACTIVE"       BOOLEAN     NOT NULL DEFAULT TRUE,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    "LAST_UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);
