name: Maven Build and Deploy

on:
  push:
    branches:
      - '**'   # All branches
  pull_request:
    branches:
      - '**'   # All branches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Maven settings.xml
      run: |
        mkdir -p $HOME/.m2
        cat > $HOME/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and deploy with Maven
      id: maven_build
      continue-on-error: ${{ github.ref != 'refs/heads/main' }}
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -DskipITs

    - name: Fail on non-main if build failed
      if: ${{ github.ref == 'refs/heads/main' && steps.maven_build.outcome != 'success' }}
      run: |
        echo "Build failed on main branch — failing workflow."
        exit 1